name: database
description: 'Drift managed database'
publish_to: none
version: 0.0.1

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=3.27.1"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.27.0
  drift_flutter: 0.2.4
  collection: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.27.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
