name: database
description: 'Drift managed database'
publish_to: none
version: 0.0.1

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=3.32.8"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  drift: 2.28.0
  drift_flutter: 0.2.5
  collection: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: 2.28.0
  build_runner: 2.5.4

flutter:
  uses-material-design: true
