name: rest_client
description: "Rest api client above Dio"
publish_to: none
version: 0.0.1

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=3.27.1"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true