name: pretty_chart
description: 'Pretty charts with animation'
publish_to: none
version: 0.0.1

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=3.27.1"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  clock:
  stack_trace:
  fl_chart: ^0.71.0
  collection: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
